### PR TITLE
Introduce a reproducible build

### PR DESCRIPTION
**Pull request by aaronmondal**
This is an initial take on introducing a fully hermetic, reproducible build for lucene-cuvs.

Broadly speaking, it does the following:

1. Get all dependencies we need, including CUDA and a base C++ toolchain.
2. Take these base dependencies to build a Clang/LLVM toolchain that is able to cross-compile for CUDA, AMDGPU and more or less any CPU architecture.
3. Build the C++ shared object using that Clang toolchain. This doesn't fully work yet and requires upstream work in the various CUDA libraries and LLVM.

Surprisingly, the only "hard" blocker are two Clang crashes which should be fixable once we get proper reproducers for upstream ready.

This also provides the infrastructure to target AMD GPUs (though the kernels need to be written first :D)

On a 12 core CPU this build takes ~40 min for a clean build. Incremental builds take ~5 min.

Also, this commit:

- Changes raft to the new cuvs repo where applicable.
- Bumps all dependencies to more or less the latest version.
- Removes redundant files (pom.xml, CMakeLists.txt, obsolete headers).

### CODE REVIEW

**Comment by aaronmondal** [comment]
@chatman Still in draft stage, but should give a decent overview.

As this essentially rewrites the entire repo I added a temporary README at https://github.com/aaronmondal/lucene-cuvs/tree/hermetic-reproducible-build.

I'll start upstreaming the various patches in the coming days. We'll also have to see whether we can create reproducers for the LLVM folks to get rid of the compiler crashes.

**Review by MarcusSorealheis — COMMENTED** [review]
Incredible.

**Comment by chatman** [comment]
Thanks Aaron, will review it this week and get back to you.

**Comment by aaronmondal** [comment]
@chatman Working now. You can find the updated README in human-readable form at https://github.com/aaronmondal/lucene-cuvs/tree/hermetic-reproducible-build

**Comment by MarcusSorealheis** [comment]
@chatman Have you reviewed this PR yet?

**Pull request closed without merging**
